[package]
name = "mdsilo"
version = "0.4.0-beta.1"
description = "mdSilo Desktop"
authors = ["dloh"]
license = "AGPL3"
repository = ""
default-run = "mdsilo"
edition = "2021"
rust-version = "1.60.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.0.0-rc.9", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "1.0.0-rc.14", features = ["clipboard-all", "dialog-all", "protocol-all", "shell-all", "window-all"] }
trash = "2.1.4"
notify = "4.0.17"
open = "2.1.3"
bincode = "1.3.3"

[dev-dependencies]
tokio = {version="1.18.2", features = ["full"] }

[features]
# by default Tauri runs in production mode
# when `tauri dev` runs it is executed with `cargo run --no-default-features` if `devPath` is an URL
default = [ "custom-protocol" ]
# this feature is used used for production builds where `devPath` points to the filesystem
# DO NOT remove this
custom-protocol = [ "tauri/custom-protocol" ]
